'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/app/lib/supabase'

export default function OnboardingPage() {
  const router = useRouter()
  const supabase = createClient()
  const [username, setUsername] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [usernameStatus, setUsernameStatus] = useState<
    'idle' | 'checking' | 'available' | 'taken'
  >('idle')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    async function check() {
      const {
        data: { user },
      } = await supabase.auth.getUser()
      if (!user) {
        router.push('/signup')
        return
      }

      const { data: profile } = await supabase
        .from('profiles')
        .select('username')
        .eq('id', user.id)
        .maybeSingle()

      if (profile) {
        const isAutoGenerated = /_[a-f0-9]{4}$/.test(profile.username)
        if (!isAutoGenerated) {
          router.push('/dashboard')
        }
      }

      // Pre-fill display name from Google account if available
      const googleName =
        user.user_metadata?.full_name || user.user_metadata?.name || ''
      if (googleName) setDisplayName(googleName)
    }
    check()
  }, [])

  async function checkUsername(value: string) {
    const cleaned = value.toLowerCase().replace(/[^a-z0-9]/g, '')
    setUsername(cleaned)
    if (cleaned.length < 3) return setUsernameStatus('idle')
    setUsernameStatus('checking')
    const { data } = await supabase
      .from('profiles')
      .select('username')
      .eq('username', cleaned)
      .maybeSingle()
    setUsernameStatus(data ? 'taken' : 'available')
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (usernameStatus !== 'available') {
      setError('Please choose an available username.')
      return
    }
    if (displayName.trim().length < 2) {
      setError('Please enter your name.')
      return
    }
    setLoading(true)
    setError('')

    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      router.push('/signup')
      return
    }

    const { error: updateError } = await supabase
      .from('profiles')
      .update({ username, display_name: displayName.trim() })
      .eq('id', user.id)

    if (updateError) {
      setError(updateError.message)
      setLoading(false)
      return
    }

    router.push('/dashboard')
  }

  return (
    <main className="obPage">
      <section className="obShell">
        <div className="brand">
          <img src="/memora-logo.png" alt="Memora" className="logo" />
        </div>

        <div className="obCard">
          <div className="obHeader">
            <div className="obEmoji">👋</div>
            <h1 className="title">
              Welcome to <span>Memora</span>
            </h1>
            <p className="subtitle">
              Set up your profile to get started. Your username becomes your
              personal link.
            </p>
          </div>

          <form onSubmit={handleSubmit}>
            <div className="field">
              <label htmlFor="displayName">What should we call you?</label>
              <div className="inputWrap">
                <input
                  id="displayName"
                  type="text"
                  value={displayName}
                  onChange={(e) => setDisplayName(e.target.value)}
                  placeholder="e.g. Adham Basha"
                  required
                  autoFocus
                />
                <span className="icon">👤</span>
              </div>
            </div>

            <div className="field">
              <label htmlFor="username">Choose a username</label>
              <div className="inputWrap">
                <input
                  id="username"
                  type="text"
                  value={username}
                  onChange={(e) => checkUsername(e.target.value)}
                  placeholder="e.g. adham"
                  required
                />
                <span className="icon">@</span>
              </div>
              {usernameStatus === 'checking' && (
                <div className="helper">Checking availability...</div>
              )}
              {usernameStatus === 'available' && (
                <div className="helper available">
                  ✓ {username}.memora.com is yours
                </div>
              )}
              {usernameStatus === 'taken' && (
                <div className="helper taken">✗ Username already taken</div>
              )}
            </div>

            {error && <div className="error">{error}</div>}

            <button className="submitBtn" type="submit" disabled={loading}>
              {loading ? 'Setting up...' : 'Get started →'}
            </button>
          </form>
        </div>
      </section>

      <style jsx>{`
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=DM+Sans:wght@300;400;500;600;700&display=swap');

        .obPage {
          --warm-white: #fdf5f7;
          --rose-blush: #f9e4ec;
          --main-rose: #c2185b;
          --rose-dark: #7a1733;
          --dark-plum: #2c1a20;
          --dusty-rose: #8a6470;
          min-height: 100vh;
          width: 100%;
          font-family: 'DM Sans', sans-serif;
          color: var(--dark-plum);
          background:
            radial-gradient(
              circle at 18% 14%,
              rgba(249, 228, 236, 0.95),
              transparent 26%
            ),
            radial-gradient(
              circle at 82% 18%,
              rgba(232, 128, 158, 0.18),
              transparent 26%
            ),
            radial-gradient(
              circle at 50% 90%,
              rgba(194, 24, 91, 0.08),
              transparent 34%
            ),
            var(--warm-white);
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 22px 14px;
          overflow-x: hidden;
        }

        .obShell {
          width: min(100%, 380px);
        }

        .brand {
          text-align: center;
          margin-bottom: 0px;
        }

        .logo {
          height: 63px;
          width: auto;
          object-fit: contain;
          display: block;
          margin: 0 auto;
        }
        .obCard {
          width: 100%;
          background: rgba(255, 255, 255, 0.72);
          border: 1px solid rgba(194, 24, 91, 0.08);
          border-radius: 24px;
          padding: 28px 22px 22px;
          box-shadow: 0 18px 44px rgba(194, 24, 91, 0.1);
          backdrop-filter: blur(16px);
        }

        .obHeader {
          text-align: center;
          margin-bottom: 24px;
        }

        .obEmoji {
          font-size: 36px;
          margin-bottom: 12px;
        }

        .title {
          font-family: 'Cormorant Garamond', serif;
          font-size: 28px;
          line-height: 1.1;
          font-weight: 700;
          color: var(--dark-plum);
          letter-spacing: -0.025em;
          margin-bottom: 8px;
        }

        .title span {
          color: var(--main-rose);
        }

        .subtitle {
          font-size: 12px;
          line-height: 1.6;
          color: var(--dusty-rose);
          font-weight: 400;
        }

        .field {
          margin-bottom: 14px;
        }

        .field label {
          display: block;
          font-size: 11px;
          font-weight: 600;
          color: var(--dark-plum);
          margin-bottom: 6px;
        }

        .inputWrap {
          position: relative;
        }

        .inputWrap input {
          width: 100%;
          height: 40px;
          border: 1px solid rgba(194, 24, 91, 0.1);
          border-radius: 11px;
          background: rgba(255, 255, 255, 0.86);
          color: var(--dark-plum);
          outline: none;
          padding: 0 40px 0 12px;
          font-size: 12px;
          font-family: 'DM Sans', sans-serif;
          font-weight: 500;
          transition: 0.22s ease;
        }

        .inputWrap input::placeholder {
          color: rgba(138, 100, 112, 0.62);
        }

        .inputWrap input:focus {
          border-color: rgba(194, 24, 91, 0.34);
          box-shadow: 0 0 0 3px rgba(194, 24, 91, 0.08);
          background: #fff;
        }

        .icon {
          position: absolute;
          right: 12px;
          top: 50%;
          transform: translateY(-50%);
          color: rgba(138, 100, 112, 0.74);
          font-size: 13px;
          pointer-events: none;
        }

        .helper {
          margin-top: 5px;
          color: var(--dusty-rose);
          font-size: 9.5px;
          line-height: 1.45;
        }

        .helper.available {
          color: #2e7d32;
          font-weight: 600;
        }

        .helper.taken {
          color: var(--main-rose);
          font-weight: 600;
        }

        .error {
          margin-bottom: 12px;
          color: var(--main-rose);
          font-size: 10.5px;
          font-weight: 600;
          line-height: 1.45;
        }

        .submitBtn {
          width: 100%;
          height: 41px;
          border: none;
          border-radius: 11px;
          background: var(--main-rose);
          color: #fff;
          font-size: 12.5px;
          font-family: 'DM Sans', sans-serif;
          font-weight: 600;
          cursor: pointer;
          box-shadow: 0 12px 24px rgba(194, 24, 91, 0.16);
          transition: 0.22s ease;
        }

        .submitBtn:hover {
          transform: translateY(-1px);
          background: var(--rose-dark);
          box-shadow: 0 16px 30px rgba(194, 24, 91, 0.2);
        }

        .submitBtn:disabled {
          opacity: 0.65;
          cursor: not-allowed;
          transform: none;
        }

        @media (max-width: 420px) {
          .obPage {
            padding: 16px 12px;
          }
          .brand {
            font-size: 27px;
            margin-bottom: 14px;
          }
          .obCard {
            padding: 22px 16px 18px;
            border-radius: 20px;
          }
          .title {
            font-size: 24px;
          }
          .inputWrap input,
          .submitBtn {
            height: 39px;
          }
        }
      `}</style>
    </main>
  )
}
