import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#444655',
        'outline-variant': '#d2c3c4',
        'tertiary-fixed': '#ffe088',
        'on-tertiary-fixed-variant': '#574500',
        'on-primary-fixed': '#281719',
        'on-tertiary-container': '#7a6100',
        'tertiary': '#735c00',
        'surface-tint': '#70585b',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f5f3c7',
        'background': '#fefccf',
        'primary-fixed': '#fbdbde',
        'tertiary-container': '#ffdf84',
        'inverse-surface': '#323214',
        'error': '#ba1a1a',
        'on-background': '#1d1d03',
        'on-surface': '#1d1d03',
        'surface-variant': '#e6e5b9',
        'surface-bright': '#fefccf',
        'on-secondary-fixed': '#191b29',
        'on-tertiary': '#ffffff',
        'primary-container': '#fadadd',
        'on-secondary': '#ffffff',
        'surface': '#fefccf',
        'on-primary-fixed-variant': '#574144',
        'secondary-fixed': '#e1e1f5',
        'outline': '#807475',
        'surface-dim': '#dedcb1',
        'primary': '#70585b',
        'secondary-container': '#e1e1f5',
        'primary-fixed-dim': '#debfc2',
        'surface-container-highest': '#e6e5b9',
        'tertiary-fixed-dim': '#e9c349',
        'on-tertiary-fixed': '#241a00',
        'on-primary-container': '#765e61',
        'inverse-primary': '#debfc2',
        'surface-container-low': '#f8f6c9',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#c5c5d8',
        'on-surface-variant': '#4f4445',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary-container': '#626374',
        'secondary': '#5c5d6e',
        'surface-container': '#f2f0c4',
        'surface-container-high': '#eceabe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'float-offset': '16px',
        unit: '8px',
        gutter: '24px',
        'container-padding-desktop': '80px',
        'container-padding-mobile': '24px',
      },
      fontFamily: {
        'headline-md':        ['"Playfair Display"', 'serif'],
        'display-lg-mobile':  ['"Playfair Display"', 'serif'],
        'label-sm':           ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md':            ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm':        ['"Playfair Display"', 'serif'],
        'display-lg':         ['"Playfair Display"', 'serif'],
        'body-lg':            ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-md':       ['32px', { lineHeight: '1.3',  fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2',  fontWeight: '700' }],
        'label-sm':          ['14px', { lineHeight: '1.2',  letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md':           ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'headline-sm':       ['24px', { lineHeight: '1.4',  fontWeight: '600' }],
        'display-lg':        ['48px', { lineHeight: '1.2',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg':           ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
      },
      boxShadow: {
        float: '0 20px 50px rgba(112, 88, 91, 0.15)',
      },
    },
  },
  plugins: [],
}

export default config
